export const COLORS = {
  white: '#ffffff',
  success: '#22c55e',
  successDark: '#16a34a',
  badgeReceitaBg: '#e6f4ea',
  badgeReceitaText: '#137333',
  danger: '#ff4d4f',
  dangerDark: '#dc2626',
  badgeDespesaBg: '#fce8e6',
  badgeDespesaText: '#c5221f',
  deleteBtnBg: '#fff0f0',
  deleteBtnBorder: '#ffccc7',
  primaryBlue: '#2563eb',
  bg: 'var(--bg)',
  border: 'var(--border)',
  codeBg: 'var(--code-bg)',
  accent: 'var(--accent)',
  accentBg: 'var(--accent-bg)',
  socialBg: 'var(--social-bg)',
  textHeading: 'var(--text-h)',
  textBody: 'var(--text)',
  shadow: 'var(--shadow)',
} as const;
