import { COLORS } from '../constants/colors';

export const styles = {
  appContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100%',
    overflow: 'hidden',
  },
  appBar: {
    height: '60px',
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 20px',
    backgroundColor: COLORS.bg,
    borderBottom: `1px solid ${COLORS.border}`,
    boxSizing: 'border-box',
    zIndex: 10,
  },
  appBarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  menuButton: {
    background: 'none',
    border: 'none',
    fontSize: '22px',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '4px',
    color: COLORS.textHeading,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s',
  },
  appBarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  appBarTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: COLORS.textHeading,
  },
  userInfo: {
    fontSize: '14px',
    color: COLORS.textBody,
  },
  logoutButton: {
    backgroundColor: COLORS.danger,
    color: COLORS.white,
    border: 'none',
    padding: '6px 12px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  mainLayout: {
    display: 'flex',
    flexDirection: 'row',
    flexGrow: 1,
    height: 'calc(100vh - 60px)',
    width: '100%',
  },
  drawer: {
    backgroundColor: COLORS.bg,
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    overflowX: 'hidden',
    overflowY: 'auto',
    transition: 'width 0.2s ease, padding 0.2s ease',
  },
  navMenu: {
    display: 'flex',
    flexDirection: 'column',
    width: '250px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 20px',
    color: COLORS.textBody,
    textDecoration: 'none',
    fontSize: '15px',
    fontWeight: '500',
    borderRadius: '8px',
    margin: '4px 10px',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
  },
  navItemActive: {
    color: COLORS.accent,
    backgroundColor: COLORS.accentBg,
    fontWeight: '600',
  },
  navItemHover: {
    backgroundColor: COLORS.socialBg,
    color: COLORS.textHeading,
  },
  content: {
    flexGrow: 1,
    backgroundColor: COLORS.codeBg,
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  card: {
    backgroundColor: COLORS.bg,
    borderRadius: '12px',
    padding: '24px',
    border: `1px solid ${COLORS.border}`,
    boxShadow: COLORS.shadow,
    textAlign: 'left',
  },
  contentTitle: {
    marginTop: 0,
    marginBottom: '12px',
    fontSize: '22px',
    color: COLORS.textHeading,
  },
  contentText: {
    color: COLORS.textBody,
    fontSize: '15px',
    lineHeight: '1.6',
    margin: 0,
  },
  peopleSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    textAlign: 'left',
  },
  sectionTitle: {
    fontSize: '24px',
    fontWeight: '600',
    color: COLORS.textHeading,
    margin: 0,
  },
  peopleGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '24px',
    alignItems: 'flex-start',
  },
  tableCard: {
    flex: '2 1 500px',
    backgroundColor: COLORS.bg,
    borderRadius: '12px',
    padding: '24px',
    border: `1px solid ${COLORS.border}`,
    boxShadow: COLORS.shadow,
  },
  formCard: {
    flex: '1 1 300px',
    backgroundColor: COLORS.bg,
    borderRadius: '12px',
    padding: '24px',
    border: `1px solid ${COLORS.border}`,
    boxShadow: COLORS.shadow,
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: COLORS.textHeading,
    marginTop: 0,
    marginBottom: '18px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  th: {
    textAlign: 'left',
    padding: '12px 14px',
    borderBottom: `2px solid ${COLORS.border}`,
    color: COLORS.textHeading,
    fontWeight: '600',
  },
  tr: {
    borderBottom: `1px solid ${COLORS.border}`,
  },
  td: {
    padding: '12px 14px',
    color: COLORS.textBody,
  },
  tdBold: {
    padding: '12px 14px',
    color: COLORS.textHeading,
    fontWeight: '500',
  },
  emptyTd: {
    padding: '24px',
    textAlign: 'center',
    color: COLORS.textBody,
  },
  deleteButton: {
    backgroundColor: COLORS.deleteBtnBg,
    color: COLORS.danger,
    border: `1px solid ${COLORS.deleteBtnBorder}`,
    padding: '5px 12px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    transition: 'all 0.2s',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: '14px',
    fontWeight: '500',
    color: COLORS.textHeading,
  },
  input: {
    padding: '10px 14px',
    borderRadius: '6px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '14px',
    backgroundColor: COLORS.white,
    color: COLORS.textHeading,
    outline: 'none',
    boxSizing: 'border-box',
    width: '100%',
  },
  selectInput: {
    padding: '10px 14px',
    borderRadius: '6px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '14px',
    backgroundColor: COLORS.white,
    color: COLORS.textHeading,
    outline: 'none',
    boxSizing: 'border-box',
    width: '100%',
    cursor: 'pointer',
  },
  badgeReceita: {
    backgroundColor: COLORS.badgeReceitaBg,
    color: COLORS.badgeReceitaText,
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '600',
    display: 'inline-block',
  },
  badgeDespesa: {
    backgroundColor: COLORS.badgeDespesaBg,
    color: COLORS.badgeDespesaText,
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '600',
    display: 'inline-block',
  },
  greenSubmitButton: {
    backgroundColor: COLORS.success,
    color: COLORS.white,
    border: 'none',
    padding: '12px',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '8px',
    transition: 'background-color 0.2s',
  },
  cardsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '20px',
    marginTop: '16px',
  },
  summaryCard: {
    flex: '1 1 220px',
    backgroundColor: COLORS.bg,
    borderRadius: '12px',
    padding: '20px',
    border: `1px solid ${COLORS.border}`,
    boxShadow: COLORS.shadow,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  summaryLabel: {
    fontSize: '14px',
    color: COLORS.textBody,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: '24px',
    fontWeight: '700',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '16px',
    paddingTop: '12px',
    borderTop: `1px solid ${COLORS.border}`,
  },
  paginationButton: {
    padding: '6px 14px',
    borderRadius: '6px',
    border: `1px solid ${COLORS.border}`,
    backgroundColor: COLORS.white,
    color: COLORS.textHeading,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    transition: 'all 0.2s',
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
    backgroundColor: COLORS.codeBg,
  },
  paginationText: {
    fontSize: '13px',
    color: COLORS.textBody,
    fontWeight: '500',
  },
  cardHeaderWithFilter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '18px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  filterControlGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  filterLabel: {
    fontSize: '13px',
    fontWeight: '500',
    color: COLORS.textBody,
  },
  filterSelect: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '13px',
    backgroundColor: COLORS.white,
    color: COLORS.textHeading,
    outline: 'none',
    cursor: 'pointer',
  }
} as const;
